# Generated by Django 5.0.4 on 2024-04-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, verbose_name='placa_patente')),
                ('timestamp', models.TextField(verbose_name='timestamp')),
                ('comments', models.TextField(verbose_name='comentarios')),
            ],
            options={
                'verbose_name': 'infracción',
                'verbose_name_plural': 'infracciones',
            },
        ),
    ]
